#pragma checksum "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "98f1e30e243039cbc86a458f822db503ce281281"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Students_Search), @"mvc.1.0.view", @"/Views/Students/Search.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\_ViewImports.cshtml"
using CodeFirst;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\_ViewImports.cshtml"
using CodeFirst.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"98f1e30e243039cbc86a458f822db503ce281281", @"/Views/Students/Search.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2893f32809c6984f1f4f51fb32c8f7d676103953", @"/Views/_ViewImports.cshtml")]
    public class Views_Students_Search : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
  
    var Students = (List<Student>)ViewData["Search"];

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h5>Students:</h5>\r\n<table class=\"table table-hover\">\r\n    <thead>\r\n        <tr>\r\n            <td>ID</td>\r\n            <td>FirstName</td>\r\n            <td>LastName</td>\r\n            <td>Email</td>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");
#nullable restore
#line 16 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
         foreach (var Student in Students)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <tr>\r\n                <td>");
#nullable restore
#line 19 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
               Write(Student.Id);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 20 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
               Write(Student.FirstName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 21 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
               Write(Student.LastName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 22 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
               Write(Student.Email);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n            </tr>\r\n");
#nullable restore
#line 24 "C:\Users\Abdullah\Desktop\Tuwaiq\ASP.NET\Homework #1\HW_Week06_Day05_Many-To-Many\CodeFirst\CodeFirst\Views\Students\Search.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("    </tbody>\r\n</table>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
