using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog_Website.Models;

namespace Blog_Website.Controllers
{
   
    public class ArticlesController : Controller
    {
        public List<ArticlesModel> Articles = new List<ArticlesModel>() {
       new ArticlesModel(1,1, "January 08, 2021", "Tesla has activated its in-car camera to monitor drivers using Autopilot","Tesla has enabled the in-car camera in its Model 3 and Model Y vehicles to monitor drivers when its Autopilot advanced driver assistance system is being used.In a software update, Tesla indicated the “cabin camera above the rearview mirror can now detect and alert driver inattentiveness while Autopilot is engaged.” Notably, Tesla has a closed loop system for the data, meaning imagery captured by the camera does not leave the car. The system cannot save or transit information unless data sharing is enabled, according to Tesla. The firmware update was cited by a number of Tesla owners, industry watchers and bloggers who are active on Twitter.Tesla has faced criticism for not activating a driver monitoring system within the vehicle even as evidence mounted that owners were misusing the system. Owners have posted dozens of videos on YouTube and TikTok abusing the Autopilot system — some of whom have filmed themselves sitting in the backseat as the vehicle drives along the highway. Several fatal crashes involving Tesla vehicles that had Autopilot engaged has put more pressure on the company to act.Until now, Tesla has not used the camera installed in its vehicles and instead relied on sensors in the steering wheel that measured torque — a method that is supposed to require the driver to keep their hands on the wheel. Drivers have documented and shared on social media how to trick the sensors into thinking a human is holding the wheel.", "https://techcrunch.com/wp-content/uploads/2019/01/tesla-cameraAutopilot.jpg?w=1390&crop=1"),
       new ArticlesModel(2,2, "May 28, 2021", "Goldman Sachs leads $45M investment into auto fintech startup MotoRefi","MotoRefi has raised another $45 million in a round led by Goldman Sachs just five months after investors poured $10 million into the fintech startup to help turbocharge its auto refinancing business. The startup developed an auto refinancing platform that handles the entire loan process, including finding the best rates, paying off the old lender and re-titling the vehicle. MotoRefi says using its platform saves consumers an average of $100 a month on their car payments, a goal achieved partly because it works directly with lending institutions. The company’s refinancing tools had seen steady growth until the COVID-19 pandemic popped into in higher gear. CEO Kevin Bennett said MotoRefi is on track to issue $1 billion in loans by the end of the year, a fivefold increase from the same period last year. Bennett said the short timeline between rounds was driven by investor confidence in its metrics, which have continued on to grow at a fast pace, and the basic economics around the business.", "https://techcrunch.com/wp-content/uploads/2019/07/GettyImages-200245146-001.jpg?w=1390&crop=1"),
       new ArticlesModel(1,3,"May 27, 2021","Japanese space company ispace aims to send landers to the moon","Tokyo-based ispace has been selected to deliver rovers from Canada and Japan to the lunar surface after they launch aboard SpaceX rockets. The company will use its recently revealed Hakuto-R lander for both missions, currently scheduled for 2022 and 2023. The Canadian Space Agency selected three private Canadian companies, each with separate scientific missions, to ride the lander. Mission Control Space Services, Canadensys and NGC are the first companies to receive awards under the CSA’s Capability Demonstration program, part of the agency’s Lunar Exploration Accelerator Program. LEAP, unveiled by the Canadian government in February 2020, earmarks $150 million over five years to support in-space demonstrations and science missions from Canadian private industry. As part of the mission, the ispace lander will deliver the United Arab Emirates’ The Mohammed Bin Rashid Space Centre (MBRSC)’s 22-pound rover, “Rashid.” The rover will be equipped with an artificial intelligence flight computer from space robotics company Mission Control Space Services. Mission Control’s AI will use deep-learning algorithms to recognize lunar geology as the Rashid rover traverses the surface. ispace will carry cameras “to capture key events during the mission” for Canadensys. The Japanese company will also collect lunar imagery data for demonstration of NGC’s autonomous navigation system. “We are honored that all three of the companies awarded by CSA have each entrusted ispace’s services to carry out their operations on the lunar surface,” ispace founder and CEO Takeshi Hakamada said in a statement. “We see this as a show of the trust that ispace has developed with CSA over the past years, as well as a recognition of ispace’s positive position in the North American market.”","https://techcrunch.com/wp-content/uploads/2021/05/06_Main_no_logo_202012_JP.jpg?w=1390&crop=1"),
       new ArticlesModel (2,4,"May 27, 2021","Lucid Motors reveals all the tech inside its all-electric Air sedan","ight months after Lucid Motors showed off the final version of its all-electric Air sedan, the company has finally revealed the in-cabin tech — from the curved 34-inch display and second touchscreen to the underlying software, integrated apps and Amazon Alexa voice assistant — that drivers and passengers will use once the automaker begins deliveries of the vehicle in the second half of the year. The aim of the company’s branded Lucid User Experience, or Lucid UX, is to include all the tech that customers might want in a vehicle priced between $80,000 and $169,000 without adding clutter and confusion. “We really tried to follow a strong principle of ease-of-use and a short learning curve, for it to have quick responses and an overall feeling of elegance,” Derek Jenkins, Lucid’s head of design said in a recent interview. “I kind of wanted to move away from it being overly technical or sci-fi looking or spreadsheet-like and really move towards something that was more fitting with the brand and our design ethos.” The interior isn’t as stark as a Tesla Model 3 or Tesla Model Y, nor as jam-packed as some of the German luxury vehicles. Jenkins and his team have tried to hit the Goldilocks’s equivalent the perfect bowl of tech porridge. “At the beginning of the project I always used to tell the team, ‘Listen I want my mom to be able to get in this car and figure it out the first time,’ ” Jenkins said. “She should be able to know instinctively probably the light switch and the door locks are on the left side because that’s where they always are and not have to dig through that stuff. Or that the climate controls are probably on the lower screen because that’s where it often is and traditionally has been. I just felt like it should have intuitiveness and a degree of simplicity, while still having impressive features and having a system that can grow.”","https://techcrunch.com/wp-content/uploads/2021/05/lucid-air-interior-04.jpg?w=1390&crop=1"),
       new ArticlesModel (3,5,"May 27, 2021","Rivian delays deliveries of the R1T Launch Edition by one month","Rivian said that deliveries of the R1T Launch Edition, the limited edition release of its first series of “electric adventure vehicles,” will be delayed by a month, according to an update on its website. Customers who preordered can now expect to start receiving their pickup trucks in July instead of June, with Launch Edition deliveries to be completed by Spring 2022. The change was first spotted by the Rivian Forum. The one-month delay was due to a combination of small issues, including delays on shipping containers, the ongoing chip shortage as well as ensuring the servicing piece is properly set up, a Rivian spokesperson said. Rivian noted that it has been largely unaffected by the chip shortage compared to the rest of the industry because its products don’t require as many as other vehicles on the market today. The Amazon-backed EV startup told preorder holders in July 2020 to expect deliveries of the truck in June 2021, with R1S electric SUV deliveries starting two months later in August. The delivery timeline has already been extended once, after Rivian suspended construction work on its factory due to the coronavirus pandemic. Rivian is working to maintain the August delivery time of the R1S, the spokesperson said. Despite the delay, it looks like Rivian will still be first to bring an electric truck to market among both new EV entrants and legacy automakers. Lordstown Motors CEO Steve Burns said in an investor call last week that deliveries for the company’s “Endurance” truck are still on track for September (despite slashing production numbers in half). Ford’s F-150 Lighting, the electric version of its nameplate pickup, is expected in 2022. And Tesla recently confirmed that its Cybertruck will start production late this year.","https://techcrunch.com/wp-content/uploads/2018/12/Rivian_R1T_Fun_In_Dirt_2.jpg?w=1390&crop=1"),
       new ArticlesModel (4,6,"May 28, 2021","Facebook changes misinfo rules to allow posts claiming COVID-19 is man-made","Facebook made a few noteworthy changes to its misinformation policies this week, including the news that the company will now allow claims that COVID was created by humans — a theory that contradicts the previously prevailing assumption that humans picked up the virus naturally from animals. “In light of ongoing investigations into the origin of COVID-19 and in consultation with public health experts, we will no longer remove the claim that COVID-19 is man-made from our apps,” a Facebook spokesperson told TechCrunch. “We’re continuing to work with health experts to keep pace with the evolving nature of the pandemic and regularly update our policies as new facts and trends emerge.” The company is adjusting its rules about pandemic misinformation in light of international investigations legitimating the theory that the virus could have escaped from a lab. While that theory clearly has enough credibility to be investigated at this point, it is often interwoven with demonstrably false misinformation about fake cures, 5G towers causing COVID and most recently the false claim that the AstraZeneca vaccine implants recipients with a Bluetooth chip. Earlier this week, President Biden ordered a multi-agency intelligence report evaluating if the virus could have accidentally leaked out of a lab in Wuhan, China. Biden called this possibility one of two “likely scenarios.” “… Shortly after I became President, in March, I had my National Security Advisor task the Intelligence Community to prepare a report on their most up-to-date analysis of the origins of COVID-19, including whether it emerged from human contact with an infected animal or from a laboratory accident,” Biden said in an official White House statement, adding that there isn’t sufficient evidence to make a final determination. Claims that the virus was man-made or lab-made have circulated widely since the pandemic’s earliest days, even as the scientific community largely maintained that the virus probably made the jump from an infected animal to a human via natural means. But many questions remain about the origins of the virus and the U.S. has yet to rule out the possibility that the virus emerged from a Chinese lab — a scenario that would be a bombshell for international relations. Prior to the COVID policy change, Facebook announced that it would finally implement harsher punishments against individuals who repeatedly peddle misinformation. The company will now throttle the News Feed reach of all posts from accounts that are found to habitually share known misinformation, restrictions it previously put in place for Pages, Groups, Instagram accounts and websites that repeatedly break the same rules.","https://techcrunch.com/wp-content/uploads/2020/03/GettyImages-1207957894.jpg?w=1390&crop=1"),
       new ArticlesModel(3,7,"May 27, 2021","Greg, an app for plant lovers, grows $5.4 million in seed funding","Before the pandemic rendered us homebound, the houseplant industry was already in bloom. One year sequestered in our homes later, and our living spaces have flourished into our personal indoor gardens. An app that uses machine learning to help people care for their plants, Greg announced today that it has received $5.4 million in seed funding. This round is led by Index with participation from First Round Capital. Greg is also backed by a team of expert angels and advisors, including Elie Seidman (previous CEO of Tinder), Eliza Blank (founder of The Sill, a plant delivery service) and Darryl Cheng (a “plant-stagrammer” with 600K followers). Currently, Greg’s remote team has 11 members and plans to hire a head of Brand and at least five more engineers, including a senior Android engineer (so far, the app is only available on iOS). Primarily, Greg works by telling people when to water their plants — that’s not something you can just set a weekly reminder for, as every plant is a bit different. Greg’s recommendations are tailored to each plant’s species, geographic location, sun exposure and proximity to a window. This makes it easy for anyone to keep their greenery thriving in any circumstance. There’s also a discover feed built into the app, where users can share photos of their plants, which have names like “Keanu Leaves” and “Michelle Branch.”For CEO, co-founder and engineer Alex Ross, plant care is more than just a pandemic hobby. Gregarious, Inc. — the company behind Greg — was founded as a public benefit corporation. In a legally-binding public statement, the team promises to produce a positive effect (“or a reduction of negative effects” — that’s where we’re at with climate change) within Earth’s ecosystems. The company’s charter outlines three goals: developing original technology and research to deepen our understanding of plant life; acting as stewards of the planet’s health; and creating opportunities for all forms of life to thrive. “Plants are a really great vehicle for understanding how the planet works,” said Ross. “That’s one of our core reasons for starting Greg. We believe that more people need to understand how ecosystems work, how plants work, and how our food system works in order for us to make better decisions as a society in the next 10 or 20 years.” This isn’t Ross’s first experience with mission-driven entrepreneurship. As a director of engineering at Tinder, he created the Trust & Safety team, which is responsible for keeping the dating app’s users safe from abuse. There, he saw the potential for consumer mobile apps to build an audience.","https://techcrunch.com/wp-content/uploads/2021/05/greg-tc.jpg?w=1390&crop=1"),

       };


        private List<UserModel> authors = new List<UserModel>() {
         new UserModel(1,"Kirsten Korosec","KirstenKorosec@gmail.com","https://res.cloudinary.com/crunchbase-production/image/upload/c_thumb,h_256,w_256,f_auto,g_faces,z_0.7,q_auto:eco/tluillv6dybajfj7i0dq","https://images.pexels.com/photos/946351/pexels-photo-946351.jpeg?w=500&h=650&auto=compress&cs=tinysrgb"),
         new UserModel(2,"Devin Coldewey","DevinColdewey@gmail.com","https://media-cldnry.s-nbcnews.com/image/upload/newscms/2014_01/95471/2503781351_7feef38a1a_b-95471.jpg","https://images.pexels.com/photos/3692749/pexels-photo-3692749.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"),
         new UserModel(3,"Rebecca Bellan","RebeccaBellan,@gmail.com","https://www.monteirolobato.edu.br/public/assets/admin/images/avatars/avatar5_big.png","https://images.pexels.com/photos/4500796/pexels-photo-4500796.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"),
         new UserModel(4,"Amanda Silberling","AmandaSilberling@gmail.com","https://kenyonreview.b-cdn.net/site/wp-content/uploads/Silberling-Amanda.jpg","https://images.pexels.com/photos/1144687/pexels-photo-1144687.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500")
       };

        public IActionResult Index(int id =-1)
        {
            ViewData["Articles"] = Articles;
            ViewData["authors"] = authors;
            ViewData["id"] = id;

            return View("Index");
        }

        public IActionResult Details(int? id)
        {
            ArticlesModel blog1 = Articles.Find(b => b.Article_id == id);

            if (blog1 == null)
            {
                return Content("Not found");
            }
            else
            {
                ViewData["Articles"] = Articles;
                ViewData["authors"] = authors;
                ViewData["id"] = id;


                return View("Details");
            }
        }
    }
}
