// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paradise.Data;

namespace Paradise.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210603173127_InsertFlowers")]
    partial class InsertFlowers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Paradise.Models.Care", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LevelCare")
                        .HasColumnType("text");

                    b.Property<string>("Place")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Cares");
                });

            modelBuilder.Entity("Paradise.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Paradise.Models.Flower", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Tempreture")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pink-dahlias-royalty-free-image-513204805-1562778270.jpg?crop=0.445xw:1.00xh;0.450xw,0&resize=980:*",
                            Name = "Dahlias",
                            Tempreture = "20°–22°C"
                        },
                        new
                        {
                            ID = 2,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cornflowers-royalty-free-image-104696040-1562778695.jpg?crop=0.445xw:1.00xh;0.386xw,0&resize=980:*",
                            Name = "Cornflower",
                            Tempreture = "15°-26°C"
                        },
                        new
                        {
                            ID = 3,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cosmos-flowers-royalty-free-image-184971248-1562779148.jpg?crop=0.445xw:1.00xh;0.382xw,0&resize=980:*",
                            Name = "Cosmos",
                            Tempreture = "16°C"
                        },
                        new
                        {
                            ID = 4,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/verbena-royalty-free-image-471346036-1562778134.jpg?crop=0.445xw:1.00xh;0.439xw,0&resize=980:*",
                            Name = "Verbena",
                            Tempreture = "15°C"
                        },
                        new
                        {
                            ID = 5,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/colchicum-autumnale-autumn-crocus-1532630291.jpg?crop=0.4449685534591195xw:1xh;center,top&resize=980:*",
                            Name = "Colchicum",
                            Tempreture = "20°-25°C"
                        },
                        new
                        {
                            ID = 6,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/purple-aster-daisies-1532630286.jpg?crop=0.447xw:1.00xh;0.366xw,0&resize=980:*",
                            Name = "Asters",
                            Tempreture = "16°–17°C"
                        });
                });

            modelBuilder.Entity("Paradise.Models.Plant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Tempreture")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
